# Recommended Clash Meta configuration for Iran - anti-DNS hijack, fake-ip, auto rule-providers, robust region rules

mixed-port: 7892
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false

external-controller: 0.0.0.0:9090
external-ui: ui
external-ui-url: 
  https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
secret: ''

# Performance Settings
unified-delay: false
tcp-concurrent: true
find-process-mode: strict

# Profile Settings
profile:
  store-selected: true
  store-fake-ip: true

# TUN Configuration for Iran
tun:
  enable: true
  stack: system
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  device: utun0
  mtu: 9000
  strict-route: true
  gso: true
  gso-max-size: 65536

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.ir'
  - +.aparat.com
  - +.rubika.ir
  - +.digikala.com
  - +.eitaa.com
  - +.telewebion.ir
  - +.snapp.ir
  - +.shad.ir
  - +.zarinpal.com
  - +.parsian.com
  - +.mellat.ir
  - +.bmi.ir
  - +.postbank.ir
  - +.shetab.ir
  - +.sep.ir
  - +.irna.ir
  - +.isna.ir
  use-hosts: true
  use-system-hosts: false
  respect-rules: true
  default-nameserver:
  - tls://1.1.1.1:853
  - tls://9.9.9.9:853
  nameserver:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://9.9.9.9/dns-query
  proxy-server-nameserver:
  - https://cloudflare-dns.com/dns-query
  - 1.1.1.1

proxies:
- name: OpenRay  US-10682
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  CA-4516
  type: vless
  server: 104.26.5.112
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4546
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6a-e711-455c-d273-3439ca210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4642
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  US-13270
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-13503
  type: vless
  server: 185.236.232.72
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-14426
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-15288
  type: vless
  server: 185.236.232.72
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-16867
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-16940
  type: vless
  server: 185.236.232.72
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  CA-5277
  type: vless
  server: 172.66.40.99
  port: 80
  uuid: 1fd7512a-01e5-442c-88d9-ced864e0253e
  network: ws
  ws-opts:
    path: 
      /@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy
    headers:
      Host: 
        websocket.network.www.speedtest.net.flutter.dev.russia.python.js.carwash-vip.xyz.
- name: OpenRay  CA-5291
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-5293
  type: vless
  server: 104.26.5.112
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay Dynamic-5679
  type: vless
  server: informed-location.seotoolsforyou.co.uk
  port: 80
  uuid: 5c929ec5-5b1e-447a-950c-354c5d1ba1de
  network: ws
  ws-opts:
    path: /
    headers:
      Host: informed-location.seotoolsforyou.co.uk
- name: OpenRay  US-17031
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17032
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17033
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17034
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17040
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17042
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17170
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17171
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17224
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17226
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17228
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17229
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17235
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17237
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17258
  type: vless
  server: 185.236.232.72
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17261
  type: vless
  server: 185.236.232.72
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  CA-5347
  type: vless
  server: 51.222.158.206
  port: 80
  uuid: cef1e956-e92b-4dbb-999a-6524679f8a40
  network: ws
  ws-opts:
    path: /vless/
    headers:
      Host: '---@External_Net---@External_Net---@External_Net---@External_Net---@External_Net'
- name: OpenRay  CA-5362
  type: vless
  server: 104.26.5.112
  port: 2052
  uuid: 95260b6a-e711-455c-d273-3439ca210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay Dynamic-5856
  type: vless
  server: emma-ghorestan.info
  port: 443
  uuid: cd2e9541-3fce-4d95-9bec-919d884f911e
  network: ws
  tls: true
  servername: rseyc.christopher-azyadrafte.info
  ws-opts:
    path: /tiger
    headers:
      Host: rseyc.christopher-azyadrafte.info
- name: OpenRay  US-17422
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17424
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17571
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17655
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17656
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17660
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17669
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17686
  type: vless
  server: 185.236.232.72
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17688
  type: vless
  server: 185.236.232.72
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17801
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-17831
  type: vless
  server: 185.236.232.72
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay Dynamic-4
  type: vless
  server: mark-bezanberimtehroon.info
  port: 443
  uuid: cd2e9541-3fce-4d95-9bec-919d884f911e
  network: ws
  tls: true
  servername: qxqll.thomas-azyadrafte.info
  ws-opts:
    path: /tiger
    headers:
      Host: qxqll.thomas-azyadrafte.info
- name: OpenRay Dynamic-11
  type: vless
  server: mark-bezanberimtehroon.info
  port: 443
  uuid: cd2e9541-3fce-4d95-9bec-919d884f911e
  network: ws
  tls: true
  servername: qxqll.thomas-azyadrafte.info
  ws-opts:
    path: /tiger
    headers:
      Host: qxqll.thomas-azyadrafte.info

proxy-groups:
- name: AUTO
  type: url-test
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - OpenRay  US-10682
  - OpenRay  CA-4516
  - OpenRay  CA-4546
  - OpenRay  CA-4642
  - OpenRay  US-13270
  - OpenRay  US-13503
  - OpenRay  US-14426
  - OpenRay  US-15288
  - OpenRay  US-16867
  - OpenRay  US-16940
  - OpenRay  CA-5277
  - OpenRay  CA-5291
  - OpenRay  CA-5293
  - OpenRay Dynamic-5679
  - OpenRay  US-17031
  - OpenRay  US-17032
  - OpenRay  US-17033
  - OpenRay  US-17034
  - OpenRay  US-17040
  - OpenRay  US-17042
  - OpenRay  US-17170
  - OpenRay  US-17171
  - OpenRay  US-17224
  - OpenRay  US-17226
  - OpenRay  US-17228
  - OpenRay  US-17229
  - OpenRay  US-17235
  - OpenRay  US-17237
  - OpenRay  US-17258
  - OpenRay  US-17261
  - OpenRay  CA-5347
  - OpenRay  CA-5362
  - OpenRay Dynamic-5856
  - OpenRay  US-17422
  - OpenRay  US-17424
  - OpenRay  US-17571
  - OpenRay  US-17655
  - OpenRay  US-17656
  - OpenRay  US-17660
  - OpenRay  US-17669
  - OpenRay  US-17686
  - OpenRay  US-17688
  - OpenRay  US-17801
  - OpenRay  US-17831
  - OpenRay Dynamic-4
  - OpenRay Dynamic-11
- name: PROXY
  type: select
  proxies:
  - AUTO
  - OpenRay  US-10682
  - OpenRay  CA-4516
  - OpenRay  CA-4546
  - OpenRay  CA-4642
  - OpenRay  US-13270
  - OpenRay  US-13503
  - OpenRay  US-14426
  - OpenRay  US-15288
  - OpenRay  US-16867
  - OpenRay  US-16940
  - OpenRay  CA-5277
  - OpenRay  CA-5291
  - OpenRay  CA-5293
  - OpenRay Dynamic-5679
  - OpenRay  US-17031
  - OpenRay  US-17032
  - OpenRay  US-17033
  - OpenRay  US-17034
  - OpenRay  US-17040
  - OpenRay  US-17042
  - OpenRay  US-17170
  - OpenRay  US-17171
  - OpenRay  US-17224
  - OpenRay  US-17226
  - OpenRay  US-17228
  - OpenRay  US-17229
  - OpenRay  US-17235
  - OpenRay  US-17237
  - OpenRay  US-17258
  - OpenRay  US-17261
  - OpenRay  CA-5347
  - OpenRay  CA-5362
  - OpenRay Dynamic-5856
  - OpenRay  US-17422
  - OpenRay  US-17424
  - OpenRay  US-17571
  - OpenRay  US-17655
  - OpenRay  US-17656
  - OpenRay  US-17660
  - OpenRay  US-17669
  - OpenRay  US-17686
  - OpenRay  US-17688
  - OpenRay  US-17801
  - OpenRay  US-17831
  - OpenRay Dynamic-4
  - OpenRay Dynamic-11
rules:
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,eitaa.com,DIRECT
- DOMAIN-SUFFIX,rubika.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,zarinpal.com,DIRECT
- DOMAIN-SUFFIX,parsian.com,DIRECT
- DOMAIN-SUFFIX,mellat.ir,DIRECT
- DOMAIN-SUFFIX,bmi.ir,DIRECT
- DOMAIN-SUFFIX,postbank.ir,DIRECT
- DOMAIN-SUFFIX,shetab.ir,DIRECT
- DOMAIN-SUFFIX,sep.ir,DIRECT
- DOMAIN-SUFFIX,irna.ir,DIRECT
- DOMAIN-SUFFIX,isna.ir,DIRECT
- GEOSITE,GOOGLE,PROXY
- GEOSITE,YOUTUBE,PROXY
- GEOSITE,FACEBOOK,PROXY
- GEOSITE,INSTAGRAM,PROXY
- GEOSITE,TWITTER,PROXY
- GEOSITE,TELEGRAM,PROXY
- GEOSITE,GITHUB,PROXY
- GEOSITE,CLOUDFLARE,PROXY
- GEOSITE,NETFLIX,PROXY
- GEOSITE,SPOTIFY,PROXY
- GEOSITE,CATEGORY-ADS-ALL,REJECT
- GEOSITE,GEOLOCATION-!CN,PROXY
- GEOIP,PRIVATE,DIRECT
- MATCH,PROXY
hosts:
  dns.google: [8.8.8.8, 8.8.4.4]
  cloudflare-dns.com: [1.1.1.1, 1.0.0.1]
  1dot1dot1dot1.cloudflare-dns.com: [1.1.1.1, 1.0.0.1]
  www.google.com: [142.250.191.36]
  youtube.com: [142.250.191.14]
  www.youtube.com: [142.250.191.14]
  facebook.com: [157.240.11.35]
  www.facebook.com: [157.240.11.35]
  twitter.com: [104.244.42.193]
  www.twitter.com: [104.244.42.193]
  x.com: [104.244.42.193]
