# Recommended Clash Meta configuration for Iran - anti-DNS hijack, fake-ip, auto rule-providers, robust region rules

mixed-port: 7892
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false

external-controller: 0.0.0.0:9090
external-ui: ui
external-ui-url: 
  https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
secret: ''

# Performance Settings
unified-delay: false
tcp-concurrent: true
find-process-mode: strict

# Profile Settings
profile:
  store-selected: true
  store-fake-ip: true

# TUN Configuration for Iran
tun:
  enable: true
  stack: system
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  device: utun0
  mtu: 9000
  strict-route: true
  gso: true
  gso-max-size: 65536

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.ir'
  - +.aparat.com
  - +.rubika.ir
  - +.digikala.com
  - +.eitaa.com
  - +.telewebion.ir
  - +.snapp.ir
  - +.shad.ir
  - +.zarinpal.com
  - +.parsian.com
  - +.mellat.ir
  - +.bmi.ir
  - +.postbank.ir
  - +.shetab.ir
  - +.sep.ir
  - +.irna.ir
  - +.isna.ir
  use-hosts: true
  use-system-hosts: false
  respect-rules: true
  default-nameserver:
  - tls://1.1.1.1:853
  - tls://9.9.9.9:853
  nameserver:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://9.9.9.9/dns-query
  proxy-server-nameserver:
  - https://cloudflare-dns.com/dns-query
  - 1.1.1.1

proxies:
- name: OpenRay  US-3760
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-3928
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  FR-157
  type: vless
  server: 185.231.205.231
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  network: grpc
- name: OpenRay  US-7095
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-7343
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-8193
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay Dynamic-11
  type: vless
  server: ru.sfasti.ru
  port: 443
  uuid: 1a6fe500-59da-4598-8576-256f06765ffb
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: ru.sfasti.ru
  reality-opts:
    public-key: J_jQq9-SWQZjiMhuPaFV7V2MaJ4pkKgVRaz7x6tmvy8
    short-id: 16895459a2c7768d
  client-fingerprint: chrome
- name: OpenRay  US-9007
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-9034
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-9277
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-10052
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-10174
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-10183
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay Dynamic-20
  type: vless
  server: ru.sfasti.ru
  port: 443
  uuid: 1a6fe500-59da-4598-8576-256f06765ffb
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: ru.sfasti.ru
  reality-opts:
    public-key: J_jQq9-SWQZjiMhuPaFV7V2MaJ4pkKgVRaz7x6tmvy8
    short-id: 16895459a2c7768d
  client-fingerprint: chrome
- name: OpenRay  US-10107
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-10145
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-10150
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-10205
  type: vless
  server: 185.236.232.72
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-10648
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-10819
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay Dynamic-8
  type: vless
  server: ru.sfasti.ru
  port: 443
  uuid: 6fae85ca-395a-4f27-9eb2-75123befc475
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: ru.sfasti.ru
  reality-opts:
    public-key: J_jQq9-SWQZjiMhuPaFV7V2MaJ4pkKgVRaz7x6tmvy8
    short-id: 16895459a2c7768d
  client-fingerprint: chrome
- name: OpenRay  US-10647
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-10682
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-10704
  type: vless
  server: 185.236.232.72
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-10818
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-10860
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  CA-4483
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6a-e711-455c-d273-3439ca210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4484
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6a-e711-455c-d273-3439ca210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4514
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6a-e711-455c-d273-3439ca210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4516
  type: vless
  server: 104.26.5.112
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4517
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4546
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6a-e711-455c-d273-3439ca210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4582
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4642
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4670
  type: vless
  server: 104.26.5.112
  port: 2052
  uuid: 95260b6a-e711-455c-d273-3439ca210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4673
  type: vless
  server: 104.26.5.112
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4675
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4698
  type: vless
  server: 172.67.72.39
  port: 2052
  uuid: 95260b6a-e711-455c-d273-3439ca210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4713
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4740
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4743
  type: vless
  server: 104.26.5.112
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4762
  type: vless
  server: 104.26.5.112
  port: 2052
  uuid: 95260b6a-e711-455c-d273-3439ca210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4860
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6a-e711-455c-d273-3439ca210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4908
  type: vless
  server: 104.26.5.112
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4909
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6a-e711-455c-d273-3439ca210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4964
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4965
  type: vless
  server: 104.17.147.22
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4966
  type: vless
  server: 104.26.5.112
  port: 2052
  uuid: 95260b6%61-%65711-455c-d273-3439c%61210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir
- name: OpenRay  CA-4995
  type: vless
  server: 104.26.4.112
  port: 2052
  uuid: 95260b6a-e711-455c-d273-3439ca210d44
  network: ws
  ws-opts:
    path: 
      /@vmessorg----@vmessorg-----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg----@vmessorg?ed=2480
    headers:
      Host: Vmessorg.paradoxone.ir

proxy-groups:
- name: AUTO
  type: url-test
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - OpenRay  US-3760
  - OpenRay  US-3928
  - OpenRay  FR-157
  - OpenRay  US-7095
  - OpenRay  US-7343
  - OpenRay  US-8193
  - OpenRay Dynamic-11
  - OpenRay  US-9007
  - OpenRay  US-9034
  - OpenRay  US-9277
  - OpenRay  US-10052
  - OpenRay  US-10174
  - OpenRay  US-10183
  - OpenRay Dynamic-20
  - OpenRay  US-10107
  - OpenRay  US-10145
  - OpenRay  US-10150
  - OpenRay  US-10205
  - OpenRay  US-10648
  - OpenRay  US-10819
  - OpenRay Dynamic-8
  - OpenRay  US-10647
  - OpenRay  US-10682
  - OpenRay  US-10704
  - OpenRay  US-10818
  - OpenRay  US-10860
  - OpenRay  CA-4483
  - OpenRay  CA-4484
  - OpenRay  CA-4514
  - OpenRay  CA-4516
  - OpenRay  CA-4517
  - OpenRay  CA-4546
  - OpenRay  CA-4582
  - OpenRay  CA-4642
  - OpenRay  CA-4670
  - OpenRay  CA-4673
  - OpenRay  CA-4675
  - OpenRay  CA-4698
  - OpenRay  CA-4713
  - OpenRay  CA-4740
  - OpenRay  CA-4743
  - OpenRay  CA-4762
  - OpenRay  CA-4860
  - OpenRay  CA-4908
  - OpenRay  CA-4909
  - OpenRay  CA-4964
  - OpenRay  CA-4965
  - OpenRay  CA-4966
  - OpenRay  CA-4995
- name: PROXY
  type: select
  proxies:
  - AUTO
  - OpenRay  US-3760
  - OpenRay  US-3928
  - OpenRay  FR-157
  - OpenRay  US-7095
  - OpenRay  US-7343
  - OpenRay  US-8193
  - OpenRay Dynamic-11
  - OpenRay  US-9007
  - OpenRay  US-9034
  - OpenRay  US-9277
  - OpenRay  US-10052
  - OpenRay  US-10174
  - OpenRay  US-10183
  - OpenRay Dynamic-20
  - OpenRay  US-10107
  - OpenRay  US-10145
  - OpenRay  US-10150
  - OpenRay  US-10205
  - OpenRay  US-10648
  - OpenRay  US-10819
  - OpenRay Dynamic-8
  - OpenRay  US-10647
  - OpenRay  US-10682
  - OpenRay  US-10704
  - OpenRay  US-10818
  - OpenRay  US-10860
  - OpenRay  CA-4483
  - OpenRay  CA-4484
  - OpenRay  CA-4514
  - OpenRay  CA-4516
  - OpenRay  CA-4517
  - OpenRay  CA-4546
  - OpenRay  CA-4582
  - OpenRay  CA-4642
  - OpenRay  CA-4670
  - OpenRay  CA-4673
  - OpenRay  CA-4675
  - OpenRay  CA-4698
  - OpenRay  CA-4713
  - OpenRay  CA-4740
  - OpenRay  CA-4743
  - OpenRay  CA-4762
  - OpenRay  CA-4860
  - OpenRay  CA-4908
  - OpenRay  CA-4909
  - OpenRay  CA-4964
  - OpenRay  CA-4965
  - OpenRay  CA-4966
  - OpenRay  CA-4995
rules:
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,eitaa.com,DIRECT
- DOMAIN-SUFFIX,rubika.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,zarinpal.com,DIRECT
- DOMAIN-SUFFIX,parsian.com,DIRECT
- DOMAIN-SUFFIX,mellat.ir,DIRECT
- DOMAIN-SUFFIX,bmi.ir,DIRECT
- DOMAIN-SUFFIX,postbank.ir,DIRECT
- DOMAIN-SUFFIX,shetab.ir,DIRECT
- DOMAIN-SUFFIX,sep.ir,DIRECT
- DOMAIN-SUFFIX,irna.ir,DIRECT
- DOMAIN-SUFFIX,isna.ir,DIRECT
- GEOSITE,GOOGLE,PROXY
- GEOSITE,YOUTUBE,PROXY
- GEOSITE,FACEBOOK,PROXY
- GEOSITE,INSTAGRAM,PROXY
- GEOSITE,TWITTER,PROXY
- GEOSITE,TELEGRAM,PROXY
- GEOSITE,GITHUB,PROXY
- GEOSITE,CLOUDFLARE,PROXY
- GEOSITE,NETFLIX,PROXY
- GEOSITE,SPOTIFY,PROXY
- GEOSITE,CATEGORY-ADS-ALL,REJECT
- GEOSITE,GEOLOCATION-!CN,PROXY
- GEOIP,PRIVATE,DIRECT
- MATCH,PROXY
hosts:
  dns.google: [8.8.8.8, 8.8.4.4]
  cloudflare-dns.com: [1.1.1.1, 1.0.0.1]
  1dot1dot1dot1.cloudflare-dns.com: [1.1.1.1, 1.0.0.1]
  www.google.com: [142.250.191.36]
  youtube.com: [142.250.191.14]
  www.youtube.com: [142.250.191.14]
  facebook.com: [157.240.11.35]
  www.facebook.com: [157.240.11.35]
  twitter.com: [104.244.42.193]
  www.twitter.com: [104.244.42.193]
  x.com: [104.244.42.193]
