# Recommended Clash Meta configuration for Iran - anti-DNS hijack, fake-ip, auto rule-providers, robust region rules

mixed-port: 7892
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false

external-controller: 0.0.0.0:9090
external-ui: ui
external-ui-url: 
  https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
secret: ''

# Performance Settings
unified-delay: false
tcp-concurrent: true
find-process-mode: strict

# Profile Settings
profile:
  store-selected: true
  store-fake-ip: true

# TUN Configuration for Iran
tun:
  enable: true
  stack: system
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  device: utun0
  mtu: 9000
  strict-route: true
  gso: true
  gso-max-size: 65536

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.ir'
  - +.aparat.com
  - +.rubika.ir
  - +.digikala.com
  - +.eitaa.com
  - +.telewebion.ir
  - +.snapp.ir
  - +.shad.ir
  - +.zarinpal.com
  - +.parsian.com
  - +.mellat.ir
  - +.bmi.ir
  - +.postbank.ir
  - +.shetab.ir
  - +.sep.ir
  - +.irna.ir
  - +.isna.ir
  use-hosts: true
  use-system-hosts: false
  respect-rules: true
  default-nameserver:
  - tls://1.1.1.1:853
  - tls://9.9.9.9:853
  nameserver:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://9.9.9.9/dns-query
  proxy-server-nameserver:
  - https://cloudflare-dns.com/dns-query
  - 1.1.1.1

proxies:
- name: OpenRay  US-931
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-1327
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-2463
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-2576
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay Dynamic-3358
  type: vless
  server: tgju.org
  port: 80
  uuid: c6a58e27-6c00-4e94-de47-52fbff53d86f
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: fin.channel.digicyber.click
- name: OpenRay Dynamic-3405
  type: vless
  server: chat.deepseek.com
  port: 80
  uuid: c6a58e27-6c00-4e94-de47-52fbff53d86f
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: fin.channel.digicyber.click
- name: OpenRay Dynamic-3413
  type: vless
  server: tgju.org
  port: 80
  uuid: c6a58e27-6c00-4e94-de47-52fbff53d86f
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: fin.channel.digicyber.click
- name: OpenRay Dynamic-3455
  type: vless
  server: cafearz.com
  port: 8080
  uuid: 4c266f5d-5836-4417-d5ab-f253ca9de933
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: shad.ir.fin.test.digicyber.click.
- name: OpenRay Dynamic-3646
  type: vless
  server: chat.openai.com
  port: 8080
  uuid: 4c266f5d-5836-4417-d5ab-f253ca9de933
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: shad.ir.fin.test.digicyber.click.
- name: OpenRay Dynamic-3961
  type: vless
  server: chat.deepseek.com
  port: 80
  uuid: c6a58e27-6c00-4e94-de47-52fbff53d86f
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: fin.channel.digicyber.click
- name: OpenRay Dynamic-4109
  type: vless
  server: chat.openai.com
  port: 8080
  uuid: 4c266f5d-5836-4417-d5ab-f253ca9de933
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: shad.ir.fin.test.digicyber.click.
- name: OpenRay Dynamic-4229
  type: vless
  server: chat.deepseek.com
  port: 80
  uuid: c6a58e27-6c00-4e94-de47-52fbff53d86f
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: fin.channel.digicyber.click
- name: OpenRay Dynamic-4231
  type: vless
  server: tgju.org
  port: 80
  uuid: c6a58e27-6c00-4e94-de47-52fbff53d86f
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: fin.channel.digicyber.click
- name: OpenRay  US-1578
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-1832
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-1875
  type: vless
  server: 185.236.232.72
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-2461
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-2582
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-2886
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay Dynamic-2918
  type: vless
  server: chat.deepseek.com
  port: 80
  uuid: c6a58e27-6c00-4e94-de47-52fbff53d86f
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: fin.channel.digicyber.click
- name: OpenRay  US-3280
  type: vless
  server: 185.236.232.72
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  GB-13
  type: vless
  server: 57.129.132.223
  port: 80
  uuid: dbb78c94-9f87-4d7d-b945-2000b60352fd
  network: ws
  ws-opts:
    path: /vless/
    headers:
      Host: '---@External_Net---@External_Net---@External_Net---@External_Net---@External_Net'
- name: OpenRay Dynamic-2904
  type: vless
  server: chat.openai.com
  port: 8080
  uuid: 4c266f5d-5836-4417-d5ab-f253ca9de933
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: shad.ir.fin.test.digicyber.click.
- name: OpenRay Dynamic-2987
  type: vless
  server: chat.deepseek.com
  port: 80
  uuid: c6a58e27-6c00-4e94-de47-52fbff53d86f
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: fin.channel.digicyber.click
- name: OpenRay Dynamic-3058
  type: vless
  server: chat.deepseek.com
  port: 80
  uuid: c6a58e27-6c00-4e94-de47-52fbff53d86f
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: fin.channel.digicyber.click
- name: OpenRay Dynamic-2949
  type: vless
  server: tgju.org
  port: 80
  uuid: c6a58e27-6c00-4e94-de47-52fbff53d86f
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: fin.channel.digicyber.click
- name: OpenRay  FR-1002
  type: vless
  server: 185.231.205.186
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  network: grpc
- name: 'OpenRay Dynamic-2949 #2'
  type: vless
  server: cafearz.com
  port: 8080
  uuid: 4c266f5d-5836-4417-d5ab-f253ca9de933
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: shad.ir.fin.test.digicyber.click.
- name: OpenRay Dynamic-2950
  type: vless
  server: cafearz.com
  port: 8080
  uuid: 4c266f5d-5836-4417-d5ab-f253ca9de933
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: shad.ir.fin.test.digicyber.click.
- name: OpenRay  XX-1
  type: vless
  server: obedient-menu.seotoolsforyou.co.uk
  port: 80
  uuid: 561623c8-4983-44d3-a6ef-92b803a74ee8
  network: ws
  ws-opts:
    path: /?ed=2048@FREE_VPN02--@FREE_VPN02
    headers:
      Host: obedient-menu.seotoolsforyou.co.uk
- name: OpenRay Dynamic-2979
  type: vless
  server: chat.deepseek.com
  port: 80
  uuid: c6a58e27-6c00-4e94-de47-52fbff53d86f
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: fin.channel.digicyber.click
- name: OpenRay Dynamic-2980
  type: vless
  server: tgju.org
  port: 80
  uuid: c6a58e27-6c00-4e94-de47-52fbff53d86f
  network: ws
  ws-opts:
    path: /olem/ws?ed=1024
    headers:
      Host: fin.channel.digicyber.click
- name: OpenRay Dynamic-3654
  type: vless
  server: fruitful-exchange.seotoolsforyou.co.uk
  port: 80
  uuid: 9570a079-f83f-4454-88d0-884057c57a35
  network: ws
  ws-opts:
    path: /
    headers:
      Host: fruitful-exchange.seotoolsforyou.co.uk
- name: OpenRay  US-3722
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay  US-3823
  type: vless
  server: 185.236.232.199
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  network: grpc
- name: OpenRay Dynamic-3162
  type: vless
  server: informed-location.seotoolsforyou.co.uk
  port: 80
  uuid: 5c929ec5-5b1e-447a-950c-354c5d1ba1de
  network: ws
  ws-opts:
    path: 
      /?Join---i10VPN---Join---i10VPN---Join---i10VPN---Join---i10VPN?ed=2560
    headers:
      Host: informed-location.seotoolsforyou.co.uk
- name: OpenRay Dynamic-3163
  type: vless
  server: confident-club.seotoolsforyou.co.uk
  port: 80
  uuid: 9926ee97-4398-48dd-b263-2863c62f5c41
  network: ws
  ws-opts:
    path: 
      /?Join---MARAMBASHI---Join---MARAMBASHI---Join---MARAMBASHI---Join---MARAMBASHI?ed
    headers:
      Host: confident-club.seotoolsforyou.co.uk
- name: OpenRay Dynamic-3171
  type: vless
  server: communal-loss.oneeat.co
  port: 80
  uuid: a2af50d9-09c7-4a44-90d0-42da35923e9e
  network: ws
  ws-opts:
    path: /
    headers:
      Host: communal-loss.oneeat.co
- name: OpenRay Dynamic-3172
  type: vless
  server: confident-club.seotoolsforyou.co.uk
  port: 80
  uuid: 9926ee97-4398-48dd-b263-2863c62f5c41
  network: ws
  ws-opts:
    path: /
    headers:
      Host: confident-club.seotoolsforyou.co.uk
- name: OpenRay Dynamic-3178
  type: vless
  server: handsome-device.oneeat.co
  port: 80
  uuid: 2ad87f95-7a0b-4018-8497-5ecaac2f0ddf
  network: ws
  ws-opts:
    path: /
    headers:
      Host: handsome-device.oneeat.co
- name: OpenRay Dynamic-3179
  type: vless
  server: communal-loss.oneeat.co
  port: 80
  uuid: a2af50d9-09c7-4a44-90d0-42da35923e9e
  network: ws
  ws-opts:
    path: /
    headers:
      Host: communal-loss.oneeat.co
- name: OpenRay Dynamic-3182
  type: vless
  server: handsome-device.oneeat.co
  port: 80
  uuid: 2ad87f95-7a0b-4018-8497-5ecaac2f0ddf
  network: ws
  ws-opts:
    path: /
    headers:
      Host: handsome-device.oneeat.co
- name: OpenRay Dynamic-3183
  type: vless
  server: communal-loss.oneeat.co
  port: 80
  uuid: a2af50d9-09c7-4a44-90d0-42da35923e9e
  network: ws
  ws-opts:
    path: /
    headers:
      Host: communal-loss.oneeat.co
- name: OpenRay Dynamic-3186
  type: vless
  server: handsome-device.oneeat.co
  port: 80
  uuid: 2ad87f95-7a0b-4018-8497-5ecaac2f0ddf
  network: ws
  ws-opts:
    path: /
    headers:
      Host: handsome-device.oneeat.co
- name: OpenRay Dynamic-3187
  type: vless
  server: handsome-device.oneeat.co
  port: 80
  uuid: 2ad87f95-7a0b-4018-8497-5ecaac2f0ddf
  network: ws
  ws-opts:
    path: /
    headers:
      Host: handsome-device.oneeat.co
- name: OpenRay Dynamic-3191
  type: vless
  server: communal-loss.oneeat.co
  port: 80
  uuid: a2af50d9-09c7-4a44-90d0-42da35923e9e
  network: ws
  ws-opts:
    path: /
    headers:
      Host: communal-loss.oneeat.co
- name: OpenRay Dynamic-3197
  type: vless
  server: handsome-device.oneeat.co
  port: 80
  uuid: 2ad87f95-7a0b-4018-8497-5ecaac2f0ddf
  network: ws
  ws-opts:
    path: /
    headers:
      Host: handsome-device.oneeat.co
- name: OpenRay Dynamic-3217
  type: vless
  server: bewildered-poem.seotoolsforyou.co.uk
  port: 80
  uuid: 0f4865d9-9405-4703-a282-46e326e6d9e7
  network: ws
  ws-opts:
    path: /
    headers:
      Host: bewildered-poem.seotoolsforyou.co.uk
- name: OpenRay Dynamic-3225
  type: vless
  server: fruitful-exchange.seotoolsforyou.co.uk
  port: 80
  uuid: 9570a079-f83f-4454-88d0-884057c57a35
  network: ws
  ws-opts:
    path: /
    headers:
      Host: fruitful-exchange.seotoolsforyou.co.uk
- name: OpenRay Dynamic-3249
  type: vless
  server: handsome-device.oneeat.co
  port: 80
  uuid: 2ad87f95-7a0b-4018-8497-5ecaac2f0ddf
  network: ws
  ws-opts:
    path: /
    headers:
      Host: handsome-device.oneeat.co

proxy-groups:
- name: AUTO
  type: url-test
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - OpenRay  US-931
  - OpenRay  US-1327
  - OpenRay  US-2463
  - OpenRay  US-2576
  - OpenRay Dynamic-3358
  - OpenRay Dynamic-3405
  - OpenRay Dynamic-3413
  - OpenRay Dynamic-3455
  - OpenRay Dynamic-3646
  - OpenRay Dynamic-3961
  - OpenRay Dynamic-4109
  - OpenRay Dynamic-4229
  - OpenRay Dynamic-4231
  - OpenRay  US-1578
  - OpenRay  US-1832
  - OpenRay  US-1875
  - OpenRay  US-2461
  - OpenRay  US-2582
  - OpenRay  US-2886
  - OpenRay Dynamic-2918
  - OpenRay  US-3280
  - OpenRay  GB-13
  - OpenRay Dynamic-2904
  - OpenRay Dynamic-2987
  - OpenRay Dynamic-3058
  - OpenRay Dynamic-2949
  - OpenRay  FR-1002
  - 'OpenRay Dynamic-2949 #2'
  - OpenRay Dynamic-2950
  - OpenRay  XX-1
  - OpenRay Dynamic-2979
  - OpenRay Dynamic-2980
  - OpenRay Dynamic-3654
  - OpenRay  US-3722
  - OpenRay  US-3823
  - OpenRay Dynamic-3162
  - OpenRay Dynamic-3163
  - OpenRay Dynamic-3171
  - OpenRay Dynamic-3172
  - OpenRay Dynamic-3178
  - OpenRay Dynamic-3179
  - OpenRay Dynamic-3182
  - OpenRay Dynamic-3183
  - OpenRay Dynamic-3186
  - OpenRay Dynamic-3187
  - OpenRay Dynamic-3191
  - OpenRay Dynamic-3197
  - OpenRay Dynamic-3217
  - OpenRay Dynamic-3225
  - OpenRay Dynamic-3249
- name: PROXY
  type: select
  proxies:
  - AUTO
  - OpenRay  US-931
  - OpenRay  US-1327
  - OpenRay  US-2463
  - OpenRay  US-2576
  - OpenRay Dynamic-3358
  - OpenRay Dynamic-3405
  - OpenRay Dynamic-3413
  - OpenRay Dynamic-3455
  - OpenRay Dynamic-3646
  - OpenRay Dynamic-3961
  - OpenRay Dynamic-4109
  - OpenRay Dynamic-4229
  - OpenRay Dynamic-4231
  - OpenRay  US-1578
  - OpenRay  US-1832
  - OpenRay  US-1875
  - OpenRay  US-2461
  - OpenRay  US-2582
  - OpenRay  US-2886
  - OpenRay Dynamic-2918
  - OpenRay  US-3280
  - OpenRay  GB-13
  - OpenRay Dynamic-2904
  - OpenRay Dynamic-2987
  - OpenRay Dynamic-3058
  - OpenRay Dynamic-2949
  - OpenRay  FR-1002
  - 'OpenRay Dynamic-2949 #2'
  - OpenRay Dynamic-2950
  - OpenRay  XX-1
  - OpenRay Dynamic-2979
  - OpenRay Dynamic-2980
  - OpenRay Dynamic-3654
  - OpenRay  US-3722
  - OpenRay  US-3823
  - OpenRay Dynamic-3162
  - OpenRay Dynamic-3163
  - OpenRay Dynamic-3171
  - OpenRay Dynamic-3172
  - OpenRay Dynamic-3178
  - OpenRay Dynamic-3179
  - OpenRay Dynamic-3182
  - OpenRay Dynamic-3183
  - OpenRay Dynamic-3186
  - OpenRay Dynamic-3187
  - OpenRay Dynamic-3191
  - OpenRay Dynamic-3197
  - OpenRay Dynamic-3217
  - OpenRay Dynamic-3225
  - OpenRay Dynamic-3249
rules:
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,eitaa.com,DIRECT
- DOMAIN-SUFFIX,rubika.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,zarinpal.com,DIRECT
- DOMAIN-SUFFIX,parsian.com,DIRECT
- DOMAIN-SUFFIX,mellat.ir,DIRECT
- DOMAIN-SUFFIX,bmi.ir,DIRECT
- DOMAIN-SUFFIX,postbank.ir,DIRECT
- DOMAIN-SUFFIX,shetab.ir,DIRECT
- DOMAIN-SUFFIX,sep.ir,DIRECT
- DOMAIN-SUFFIX,irna.ir,DIRECT
- DOMAIN-SUFFIX,isna.ir,DIRECT
- GEOSITE,GOOGLE,PROXY
- GEOSITE,YOUTUBE,PROXY
- GEOSITE,FACEBOOK,PROXY
- GEOSITE,INSTAGRAM,PROXY
- GEOSITE,TWITTER,PROXY
- GEOSITE,TELEGRAM,PROXY
- GEOSITE,GITHUB,PROXY
- GEOSITE,CLOUDFLARE,PROXY
- GEOSITE,NETFLIX,PROXY
- GEOSITE,SPOTIFY,PROXY
- GEOSITE,CATEGORY-ADS-ALL,REJECT
- GEOSITE,GEOLOCATION-!CN,PROXY
- GEOIP,PRIVATE,DIRECT
- MATCH,PROXY
hosts:
  dns.google: [8.8.8.8, 8.8.4.4]
  cloudflare-dns.com: [1.1.1.1, 1.0.0.1]
  1dot1dot1dot1.cloudflare-dns.com: [1.1.1.1, 1.0.0.1]
  www.google.com: [142.250.191.36]
  youtube.com: [142.250.191.14]
  www.youtube.com: [142.250.191.14]
  facebook.com: [157.240.11.35]
  www.facebook.com: [157.240.11.35]
  twitter.com: [104.244.42.193]
  www.twitter.com: [104.244.42.193]
  x.com: [104.244.42.193]
