# Recommended Clash Meta configuration for Iran - anti-DNS hijack, fake-ip, auto rule-providers, robust region rules

mixed-port: 7892
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false

external-controller: 0.0.0.0:9090
external-ui: ui
external-ui-url: 
  https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
secret: ''

# Performance Settings
unified-delay: false
tcp-concurrent: true
find-process-mode: strict

# Profile Settings
profile:
  store-selected: true
  store-fake-ip: true

# TUN Configuration for Iran
tun:
  enable: true
  stack: system
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  device: utun0
  mtu: 9000
  strict-route: true
  gso: true
  gso-max-size: 65536

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.ir'
  - +.aparat.com
  - +.rubika.ir
  - +.digikala.com
  - +.eitaa.com
  - +.telewebion.ir
  - +.snapp.ir
  - +.shad.ir
  - +.zarinpal.com
  - +.parsian.com
  - +.mellat.ir
  - +.bmi.ir
  - +.postbank.ir
  - +.shetab.ir
  - +.sep.ir
  - +.irna.ir
  - +.isna.ir
  use-hosts: true
  use-system-hosts: false
  respect-rules: true
  default-nameserver:
  - tls://1.1.1.1:853
  - tls://9.9.9.9:853
  nameserver:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://9.9.9.9/dns-query
  proxy-server-nameserver:
  - https://cloudflare-dns.com/dns-query
  - 1.1.1.1

proxies:
- name: OpenRay Dynamic-2550
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh23v3.hiddendom.shop
- name: OpenRay Dynamic-2552
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh23v7.hiddendom.shop
- name: OpenRay Dynamic-2553
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh24v6.hiddendom.shop
- name: OpenRay Dynamic-2554
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh28v5.hiddendom.shop
- name: OpenRay Dynamic-2676
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh23v7.hiddendom.shop
- name: OpenRay Dynamic-2716
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh24v7.hiddendom.shop
- name: OpenRay Dynamic-2755
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh30v7.hiddendom.shop
- name: OpenRay Dynamic-2758
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh28v1.hiddendom.shop
- name: OpenRay Dynamic-2783
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh30v3.hiddendom.shop
- name: OpenRay Dynamic-2784
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh23v7.hiddendom.shop
- name: OpenRay Dynamic-2834
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh30v3.hiddendom.shop
- name: OpenRay Dynamic-2835
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh30v3.hiddendom.shop
- name: OpenRay Dynamic-2866
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh30v3.hiddendom.shop
- name: OpenRay Dynamic-2868
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh23v7.hiddendom.shop
- name: OpenRay Dynamic-2914
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh28v3.hiddendom.shop
- name: OpenRay Dynamic-2916
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh30v3.hiddendom.shop
- name: OpenRay Dynamic-2918
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh30v3.hiddendom.shop
- name: OpenRay Dynamic-2919
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh23v7.hiddendom.shop
- name: OpenRay Dynamic-3271
  type: vless
  server: tgju.org
  port: 443
  uuid: 88538870-5626-4cd7-9cda-1e0b6253c9ce
  network: ws
  tls: true
  servername: 6389113402676776506.VtNeT.infO
  ws-opts:
    path: /
    headers:
      Host: 6389113402676776506.VtNeT.infO
- name: OpenRay Dynamic-3306
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh30v3.hiddendom.shop
- name: OpenRay Dynamic-3307
  type: vless
  server: all.tellmethetrue.shop
  port: 443
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  network: grpc
  tls: true
  servername: pqh30v3.hiddendom.shop
- name: OpenRay Dynamic-3319
  type: vless
  server: tgju.org
  port: 443
  uuid: 88538870-5626-4cd7-9cda-1e0b6253c9ce
  network: ws
  tls: true
  servername: 6389113402676776513.VtNeT.infO
  ws-opts:
    path: /
    headers:
      Host: 6389113402676776513.VtNeT.infO
- name: OpenRay Dynamic-3320
  type: vless
  server: tgju.org
  port: 443
  uuid: 88538870-5626-4cd7-9cda-1e0b6253c9ce
  network: ws
  tls: true
  servername: 6389113402676776513.VtNeT.infO
  ws-opts:
    path: /
    headers:
      Host: 6389113402676776513.VtNeT.infO

proxy-groups:
- name: AUTO
  type: url-test
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - OpenRay Dynamic-2550
  - OpenRay Dynamic-2552
  - OpenRay Dynamic-2553
  - OpenRay Dynamic-2554
  - OpenRay Dynamic-2676
  - OpenRay Dynamic-2716
  - OpenRay Dynamic-2755
  - OpenRay Dynamic-2758
  - OpenRay Dynamic-2783
  - OpenRay Dynamic-2784
  - OpenRay Dynamic-2834
  - OpenRay Dynamic-2835
  - OpenRay Dynamic-2866
  - OpenRay Dynamic-2868
  - OpenRay Dynamic-2914
  - OpenRay Dynamic-2916
  - OpenRay Dynamic-2918
  - OpenRay Dynamic-2919
  - OpenRay Dynamic-3271
  - OpenRay Dynamic-3306
  - OpenRay Dynamic-3307
  - OpenRay Dynamic-3319
  - OpenRay Dynamic-3320
- name: PROXY
  type: select
  proxies:
  - AUTO
  - OpenRay Dynamic-2550
  - OpenRay Dynamic-2552
  - OpenRay Dynamic-2553
  - OpenRay Dynamic-2554
  - OpenRay Dynamic-2676
  - OpenRay Dynamic-2716
  - OpenRay Dynamic-2755
  - OpenRay Dynamic-2758
  - OpenRay Dynamic-2783
  - OpenRay Dynamic-2784
  - OpenRay Dynamic-2834
  - OpenRay Dynamic-2835
  - OpenRay Dynamic-2866
  - OpenRay Dynamic-2868
  - OpenRay Dynamic-2914
  - OpenRay Dynamic-2916
  - OpenRay Dynamic-2918
  - OpenRay Dynamic-2919
  - OpenRay Dynamic-3271
  - OpenRay Dynamic-3306
  - OpenRay Dynamic-3307
  - OpenRay Dynamic-3319
  - OpenRay Dynamic-3320
rules:
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,eitaa.com,DIRECT
- DOMAIN-SUFFIX,rubika.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,zarinpal.com,DIRECT
- DOMAIN-SUFFIX,parsian.com,DIRECT
- DOMAIN-SUFFIX,mellat.ir,DIRECT
- DOMAIN-SUFFIX,bmi.ir,DIRECT
- DOMAIN-SUFFIX,postbank.ir,DIRECT
- DOMAIN-SUFFIX,shetab.ir,DIRECT
- DOMAIN-SUFFIX,sep.ir,DIRECT
- DOMAIN-SUFFIX,irna.ir,DIRECT
- DOMAIN-SUFFIX,isna.ir,DIRECT
- GEOSITE,GOOGLE,PROXY
- GEOSITE,YOUTUBE,PROXY
- GEOSITE,FACEBOOK,PROXY
- GEOSITE,INSTAGRAM,PROXY
- GEOSITE,TWITTER,PROXY
- GEOSITE,TELEGRAM,PROXY
- GEOSITE,GITHUB,PROXY
- GEOSITE,CLOUDFLARE,PROXY
- GEOSITE,NETFLIX,PROXY
- GEOSITE,SPOTIFY,PROXY
- GEOSITE,CATEGORY-ADS-ALL,REJECT
- GEOSITE,GEOLOCATION-!CN,PROXY
- GEOIP,PRIVATE,DIRECT
- MATCH,PROXY
hosts:
  dns.google: [8.8.8.8, 8.8.4.4]
  cloudflare-dns.com: [1.1.1.1, 1.0.0.1]
  1dot1dot1dot1.cloudflare-dns.com: [1.1.1.1, 1.0.0.1]
  www.google.com: [142.250.191.36]
  youtube.com: [142.250.191.14]
  www.youtube.com: [142.250.191.14]
  facebook.com: [157.240.11.35]
  www.facebook.com: [157.240.11.35]
  twitter.com: [104.244.42.193]
  www.twitter.com: [104.244.42.193]
  x.com: [104.244.42.193]
