name: Check Proxies
on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:
permissions:
  contents: write
  actions: read
jobs:
  collector:
    uses: ./.github/workflows/collector.yml
    with:
      mode: combined
