name: Convert Proxies

on:
  push:
    paths:
      - output/all_valid_proxies.txt
      - output_iran/all_valid_proxies_for_iran.txt
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start subconverter server
        run: |
          docker run -d --name subconverter -v ${{ github.workspace }}:/data -p 25500:25500 tindy2013/subconverter
          # صبر می‌کنیم تا سرویس بالا بیاد
          sleep 8

      ##############################
      # Convert general proxies
      ##############################
      - name: Convert general proxies
        run: |
          mkdir -p ${{ github.workspace }}/output/converted
          for type in clash clashmeta quantumult quantumultx surge surfboard loon ss v2ray singbox; do
            curl "http://127.0.0.1:25500/sub?target=$type&url=file:///data/output/all_valid_proxies.txt" \
              -o "${{ github.workspace }}/output/converted/general_${type}.yaml" || true
          done

      ##############################
      # Convert Iran proxies
      ##############################
      - name: Convert Iran proxies
        run: |
          mkdir -p ${{ github.workspace }}/output_iran/converted
          for type in clash clashmeta quantumult quantumultx surge surfboard loon ss v2ray singbox; do
            curl "http://127.0.0.1:25500/sub?target=$type&url=file:///data/output_iran/all_valid_proxies_for_iran.txt" \
              -o "${{ github.workspace }}/output_iran/converted/iran_${type}.yaml" || true
          done

      ##############################
      # Stop subconverter
      ##############################
      - name: Stop subconverter
        run: |
          docker stop subconverter
          docker rm subconverter

      ##############################
      # Commit and push
      ##############################
      - name: Commit and push changes (force)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/converted/ output_iran/converted/
          git commit -m "Update converted proxy lists [skip ci]" || echo "No changes to commit"
          git push --force https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git main
