name: Convert Proxies

on:
  push:
    paths:
      - output/all_valid_proxies.txt
      - output_iran/all_valid_proxies_for_iran.txt
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create output folders
        run: |
          mkdir -p ${{ github.workspace }}/output/converted
          mkdir -p ${{ github.workspace }}/output_iran/converted

      # Convert general proxies
      - name: Convert general proxies
        run: |
          for type in clash clashmeta quantumult quantumultx surge surfboard loon ss v2ray singbox; do
            docker run --rm -v ${{ github.workspace }}/output:/app/output tindy2013/subconverter \
              sub -i /app/output/all_valid_proxies.txt -t $type -o /app/output/converted/general_${type}.yaml
            if [ ! -s "${{ github.workspace }}/output/converted/general_${type}.yaml" ]; then
              echo "Error: general_${type}.yaml is empty!"
              exit 1
            fi
          done

      # Convert Iran proxies
      - name: Convert Iran proxies
        run: |
          for type in clash clashmeta quantumult quantumultx surge surfboard loon ss v2ray singbox; do
            docker run --rm -v ${{ github.workspace }}/output_iran:/app/output tindy2013/subconverter \
              sub -i /app/output/all_valid_proxies_for_iran.txt -t $type -o /app/output/converted/iran_${type}.yaml
            if [ ! -s "${{ github.workspace }}/output_iran/converted/iran_${type}.yaml" ]; then
              echo "Error: iran_${type}.yaml is empty!"
              exit 1
            fi
          done

      # Commit and push converted files
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/converted/ output_iran/converted/
          git commit -m "Update converted proxy lists [skip ci]" || echo "No changes to commit"
          git push --force https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git main
