name: Convert Proxies

on:
  push:
    paths:
      - output/all_valid_proxies.txt
      - output_iran/all_valid_proxies_for_iran.txt
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start subconverter service
        run: |
          # Start subconverter as a service
          docker run -d --name subconverter -p 25500:25500 tindy2013/subconverter:latest
          
          # Wait for service to be ready
          sleep 10
          
          # Test if service is running
          curl -f http://localhost:25500/version || (echo "Service failed to start" && exit 1)

      ##############################
      # Convert general proxies
      ##############################
      - name: Convert general proxies
        run: |
          mkdir -p ${{ github.workspace }}/output/converted
          
          # Read the proxy file content
          PROXY_CONTENT=$(cat output/all_valid_proxies.txt | base64 -w 0)
          
          for type in clash clash-meta quantumult quantumult-x surge surfboard loon ss v2ray sing-box; do
            echo "Converting to $type format..."
            
            # Use subconverter API to convert proxies
            curl -X GET "http://localhost:25500/sub?target=$type&url=data:text/plain;base64,$PROXY_CONTENT&config=" \
              -o "${{ github.workspace }}/output/converted/$type.txt" \
              -H "User-Agent: ClashforWindows/0.18.1" \
              --fail --silent --show-error
            
            if [ $? -eq 0 ]; then
              echo "Successfully converted to $type"
            else
              echo "Failed to convert to $type"
            fi
          done

      ##############################
      # Convert Iran proxies
      ##############################
      - name: Convert Iran proxies
        run: |
          mkdir -p ${{ github.workspace }}/output_iran/converted
          
          # Read the Iran proxy file content
          PROXY_CONTENT=$(cat output_iran/all_valid_proxies_for_iran.txt | base64 -w 0)
          
          for type in clash clash-meta quantumult quantumult-x surge surfboard loon ss v2ray sing-box; do
            echo "Converting Iran proxies to $type format..."
            
            # Use subconverter API to convert proxies
            curl -X GET "http://localhost:25500/sub?target=$type&url=data:text/plain;base64,$PROXY_CONTENT&config=" \
              -o "${{ github.workspace }}/output_iran/converted/$type.txt" \
              -H "User-Agent: ClashforWindows/0.18.1" \
              --fail --silent --show-error
            
            if [ $? -eq 0 ]; then
              echo "Successfully converted Iran proxies to $type"
            else
              echo "Failed to convert Iran proxies to $type"
            fi
          done

      - name: Stop subconverter service
        run: |
          docker stop subconverter
          docker rm subconverter

      ##############################
      # Commit and push
      ##############################
      - name: Commit and push changes (force)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/converted/ output_iran/converted/
          git commit -m "Update converted proxy lists [skip ci]" || echo "No changes to commit"
          git push --force https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git main