name: Convert Proxies

on:
  push:
    paths:
      - output/all_valid_proxies.txt
      - output_iran/all_valid_proxies_for_iran.txt
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # This step starts a simple python web server on port 8000 to serve the files
      - name: Start a temporary web server
        run: |
          python3 -m http.server 8000 &

      # This step starts the subconverter container
      - name: Start subconverter server
        run: |
          docker run -d --name subconverter -p 25500:25500 tindy2013/subconverter
          # Wait for services to be ready
          sleep 8

      - name: Convert general proxies
        run: |
          mkdir -p ${{ github.workspace }}/output/converted
          for type in clash clashmeta quantumult quantumultx surge surfboard loon ss v2ray singbox; do
            curl "http://127.0.0.1:25500/sub?target=$type&url=http://127.0.0.1:8000/output/all_valid_proxies.txt" \
              -o "${{ github.workspace }}/output/converted/general_${type}.yaml" || true
          done

      - name: Convert Iran proxies
        run: |
          mkdir -p ${{ github.workspace }}/output_iran/converted
          for type in clash clashmeta quantumult quantumultx surge surfboard loon ss v2ray singbox; do
            curl "http://127.0.0.1:25500/sub?target=$type&url=http://127.0.0.1:8000/output_iran/all_valid_proxies_for_iran.txt" \
              -o "${{ github.workspace }}/output_iran/converted/iran_${type}.yaml" || true
          done

      - name: Stop subconverter
        if: always()
        run: |
          docker stop subconverter
          docker rm subconverter

      - name: Commit and push changes (force)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/converted/ output_iran/converted/
          git commit -m "Update converted proxy lists [skip ci]" || echo "No changes to commit"
          git push --force https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git main
