name: Convert Proxies

on:
  push:
    paths:
      - output/all_valid_proxies.txt
      - output_iran/all_valid_proxies_for_iran.txt
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Download and extract subconverter
      - name: Download and extract subconverter
        run: |
          curl -L -o subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/download/v0.9.0/subconverter_linux64.tar.gz
          tar -zxvf subconverter.tar.gz
          chmod +x subconverter/subconverter

      # 3. Create output directories
      - name: Create output directories
        run: |
          mkdir -p ${{ github.workspace }}/output/converted
          mkdir -p ${{ github.workspace }}/output_iran/converted

      # 4. Define proxy types
      - name: Set proxy types
        run: |
          echo "clash clashmeta quantumult quantumultx surge surfboard loon ss v2ray singbox" > proxy_types.txt

      - name: Convert proxies
        run: |
          convert_proxies() {
            input_file=$1
            output_dir=$2
            proxy_types=(clash clashmeta quantumult quantumultx surge surfboard loon ss v2ray singbox)
      
            mkdir -p "$output_dir"
      
            for type in "${proxy_types[@]}"; do
              ./subconverter/subconverter \
                -i "file://$input_file" \
                -o "$type" -f yaml -c > "$output_dir/${type}.yaml"
      
              if [ ! -s "$output_dir/${type}.yaml" ]; then
                echo "Error: ${type}.yaml is empty!"
                exit 1
              fi
            done
          }
      
          convert_proxies "${{ github.workspace }}/output/all_valid_proxies.txt" "${{ github.workspace }}/output/converted"
          convert_proxies "${{ github.workspace }}/output_iran/all_valid_proxies_for_iran.txt" "${{ github.workspace }}/output_iran/converted"


      # 7. Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/converted/ output_iran/converted/
          git commit -m "Update converted proxy lists [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git main
