name: Convert Proxies

on:
  push:
    paths:
      - output/all_valid_proxies.txt
      - output_iran/all_valid_proxies_for_iran.txt
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      ##############################
      # Convert general proxies
      ##############################
      - name: Convert general proxies
        run: |
          mkdir -p ${{ github.workspace }}/output/converted
          for type in clash clashmeta quantumult quantumultx surge surfboard loon ss v2ray singbox; do
            docker run --rm -v ${{ github.workspace }}:/data tindy2013/subconverter \
              subconverter -g -f /data/output/all_valid_proxies.txt -t $type -o /data/output/converted/$type
          done

      ##############################
      # Convert Iran proxies
      ##############################
      - name: Convert Iran proxies
        run: |
          mkdir -p ${{ github.workspace }}/output_iran/converted
          for type in clash clashmeta quantumult quantumultx surge surfboard loon ss v2ray singbox; do
            docker run --rm -v ${{ github.workspace }}:/data tindy2013/subconverter \
              subconverter -g -f /data/output_iran/all_valid_proxies_for_iran.txt -t $type -o /data/output_iran/converted/$type
          done

      ##############################
      # Commit and push
      ##############################
      - name: Commit and push changes (force)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/converted/ output_iran/converted/
          git commit -m "Update converted proxy lists [skip ci]" || echo "No changes to commit"
          git push --force https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git main
