name: Proxy Checker

# Trigger workflow
on:
  schedule:
    # Run every 3 hours (at minutes 0 of hours 0, 3, 6, 9, 12, 15, 18, 21)
    - cron: '0 */3 * * *'
  workflow_dispatch:  # Allow manual trigger

# Permissions (top-level fallback)
permissions:
  contents: write
  pull-requests: write

jobs:
  check-proxies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    # Checkout repository with full history
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
        token: ${{ github.token }}

    - name: Configure Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm

    # Run proxy checker script
    - name: Run proxy checker
      run: python proxy_checker.py

    # Create Pull Request with changes
    - name: Create Pull Request
      if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ github.token }}
        commit-message: "Update proxy lists"
        committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
        author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
        branch: auto/proxy-updates
        title: "Update proxy lists"
        body: "Automated update of proxy lists and state files."
        add-paths: |
          .state/**
          output/**
        delete-branch: true
