name: Proxy Checker

# Trigger workflow
on:
  schedule:
    # Run every 3 hours (at minutes 0 of hours 0, 3, 6, 9, 12, 15, 18, 21)
    - cron: '0 */3 * * *'
  workflow_dispatch:  # Allow manual trigger

# Permissions (top-level fallback)
permissions:
  contents: write

jobs:
  check-proxies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Checkout repository with full history
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Configure Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm

    # Run proxy checker script
    - name: Run proxy checker
      run: python proxy_checker.py

    # Commit and push changes directly to main
    - name: Commit and push changes
      run: |
        git add .state/ output/
        git commit -m "Update proxy lists [skip ci]" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
