name: Proxy Checker

# Trigger workflow
on:
  schedule:
    # Run every 3 hours (at minutes 0 of hours 0, 3, 6, 9, 12, 15, 18, 21)
    - cron: '0 */3 * * *'
  workflow_dispatch:  # Allow manual trigger

# Permissions
permissions:
  contents: write
  pull-requests: write

jobs:
  check-proxies:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository with full history
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm

    # Run proxy checker script
    - name: Run proxy checker
      run: python proxy_checker.py

    # Create Pull Request with changes
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update proxy lists"
        branch: auto/proxy-updates
        title: "Update proxy lists"
        body: "Automated update of proxy lists and state files."
        add-paths: |
          .state/**
          output/**
        delete-branch: true
